spring.application.name=Cookbook
spring.jackson.deserialization.fail-on-unknown-properties=true
app.appName = "Cookbook Backend RestAPI"
app.version = "0.0.1"
app.detaBuild = "25/08/2026 17:53"
app.build = 0
app.jdkVersion = null
app.springVersion = null
app.symbolCodeVer = "dev"
