spring.application.name=Cookbook
app.appName = "Cookbook Backend RestAPI"
app.version = "0.0.1"
app.detaBuild = "25/08/2026 17:53"
app.build = 0
app.jdkVersion = ""
app.springVersion = ""
app.symbolCodeVer = "dev"
